<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<html lang="en">
	<head>
		<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Document</title>
	</head>
<body bgcolor="#efefef" style="margin:0; padding:0">
<table style="border:transparent 0 solid;overflow:hidden;background-color:#efefef;width:100%;" border="0" width="100%" cellpadding="0" cel
	lspacing="0" align="center" valign="top">
	<tbody>
	<tr>
		<td style="padding:0;margin:0;border-spacing:0;">
			<table style="border:transparent 0 solid;overflow:hidden;border:1px solid #009688;max-width:600px;" border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top">
				<tbody>
				<tr>
					<td style="padding:0;margin:0;border-spacing:0;">
						<table border="0" width="100%" cellpadding="0" cellspacing="0" bgcolor="#009688">
							<tbody>
							<tr>
								<td width="64" height="64" align="center" valign="center">
									<img src="https://ps-sights.velu.ga/images/logo.png" alt="logo" width="36" height="36" />
								</td>
								<td width="6">&nbsp;</td>
								<td>
									<h2 style="color:white;font-family:'tahoma','arial',sans-serif;font-size:20px;">Sights map</h2>
								</td>
							</tr>
							</tbody>
						</table>
					</td>
				</tr>
				<tr>
					<td style="padding:0;margin:0;border-spacing:0;">
						<table border="0" width="100%" cellpadding="0" cellspacing="0" bgcolor="#009688">
							<tbody>
							<tr>
								<td style="padding:24px 16px;background:white;font-family:'tahoma','arial',sans-serif;font-size:14px;">%CONTENT%</td>
							</tr>
							</tbody>
						</table>
					</td>
				</tr>
				<tr>
					<td style="padding:0;margin:0;border-spacing:0;">
						<table border="0" width="100%" cellpadding="0" cellspacing="0" bgcolor="#009688">
							<tbody>
							<tr>
								<td style="padding:16px;color:#a0a0a0;background:#424242;font-family:'tahoma','arial',sans-serif;font-size:14px;">
									<p>Это письмо сгенерировано автоматически, отвечать на него не нужно.</p>
								</td>
							</tr>
							</tbody>
						</table>
					</td>
				</tr>
				</tbody>
			</table>
		</td>
	</tr>
	</tbody>
</table>
</body>
</html>